### ISSUE TITLE
API Endpoint is no longer available

### ISSUE THREAD

**Issue by jleseane23** [stacksjb/AlfredTodWorkflow#3]
I'm getting the following when trying to use the workflow. Is this still something you're supporting? 

This API endpoint is no longer available. Please refer to our documentation to upgrade your client to use the latest API version: https://developer.todoist.com

**Comment by stacksjb** [comment]
This is working perfectly fine for me, no issues. Can you manually create a task from the command line? (tod -t <taskname>)

If not, do you have the latest version of https://github.com/alanvardy/tod installed? This is just a wrapper for that; it passes the alfred arguments and items to the tod client.

**Comment by stacksjb** [comment]
If you're still having issues, please reproduce the issue with Alfred debugging enabled (open up alfred preferences, select the workflow, then click the bug icon and reproduce the issue while it says "Debugger running:") and post the log.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/2865491/206072415-aabe8e13-569c-4b33-9146-570269d6c065.png">

**Comment by jleseane23** [comment]
> This is working perfectly fine for me, no issues. Can you manually create a task from the command line? (tod -t [task name])
> 
> If not, do you have the latest version of https://github.com/alanvardy/tod installed? This is just a wrapper for that; it passes the alfred arguments and items to the tod client.

I think that's what it is. i'm updating tod now and I'll keep you updated. Thanks.

**Comment by stacksjb** [comment]
I noticed you also opened a bug against [moranje](https://github.com/moranje/alfred-workflow-todoist) that appeared the same - FYI we are entirely different projects and code, so please ensure you don't have us both enabled or are using both (or if you are, you are using different Alfred keywords)

**Comment by jleseane23** [comment]
TOD wasn't updated. my bad. Thanks for the help

**Comment by stacksjb** [comment]
Good to hear you got it figured out!
