### ISSUE TITLE
Getting querying API failure

### ISSUE THREAD

**Issue by jamie9090** [stacksjb/AlfredTodWorkflow#4]
Love this workflow, use it every day.

After updating Tod to latest version, getting a Querying API fail when creating a task via Alfred.

In Tod itself, creating a task is successful.

On latest workflow version too.

**Comment by stacksjb** [comment]
I'll take a look at this. What output do you get on the command line when running "tod -t testtask" ?

**Comment by stacksjb** [comment]
There were some changes to Todoist's API yesterday which may be related

**Comment by stacksjb** [comment]
I've determined this is due to a change in the way TOD returns the status code - it returns "Querying API" and then success/failure, which breaks the way I expect response within Alfred. Will investigate further.

**Comment by stacksjb** [comment]
In the meantime, you can manually work around this by downgrading to the previous version with the installation command of ` cargo install tod --version 0.3.1`

Note that you will probably get a task creation error once daily from the update response, but a second task creation will succeed.

**Comment by jamie9090** [comment]
Hey man! Is Tod safe to update now?

**Comment by stacksjb** [comment]
Yes - been safe since I closed this issue :)

**Comment by jamie9090** [comment]
Thank you!
