### ISSUE TITLE
make it easier to disable audio...

### ISSUE THREAD

**Issue by smagdali** [stacksjb/AlfredTodWorkflow#7]
Or at least provide easier to follow instructions than

```4) Configure your shortcut (td by default) and any notification sound(s)```

My work colleagues have also suggested OFF by default. :)

(other than that, great app, love it (I was also a long time moranje workflow  user)

**Comment by stacksjb** [comment]
As an ADHD person, need/love the dopamine hit each time I add a task :)

I'll investigate maybe adding some way of configuring that as part of the initial setup however - thx for the feedback!

**Comment by stacksjb** [comment]
I've added an initial config checkbox to enable/disable task creation sound.
I am leaving failure sound on by default as I think it is beneficial to know when creation has failed (so you can avoid losing entry)
