### ISSUE TITLE
Breaking change to Tod API

### ISSUE THREAD

**Issue by alanvardy** [stacksjb/AlfredTodWorkflow#8]
https://github.com/alanvardy/tod/pull/300#issuecomment-1519076142

From the comment:

---

@stacksjb My next tod release is a large breaking change to the Tod API. It uses commands that are inspired by GitHub CLI [cli.github.com](https://cli.github.com/) .

It means that I can separate the commands into sections, makes the commands more intuitive and easier to remember, allows future expansion and provides both flags and interactive functionality.

But it is totally going to break your workflow. Once this is released you will need to use tod issue create -p inbox -c "task text here" to create a task using your library.

How can I coordinate with you to makes this as small a breakage as possible? Perhaps I can time the release of this so that you could update your workflow at the same time.

---

**Comment by stacksjb** [comment]
Thanks for the notifications - this is resolved and latest update addresses this. Thanks for making the migration easy - simply had to change the parameters called and tests validate successfully!

**Comment by alanvardy** [comment]
> Thanks for the notifications - this is resolved and latest update addresses this. Thanks for making the migration easy - simply had to change the parameters called and tests validate successfully!

Great, thanks for working with me on it!
